### ISSUE TITLE
Mouseover NotGrid doesn't work in Combat

### ISSUE THREAD

**Issue by mohcow** [DennisWG/CastModifier#24]
hi, mouseover macros doesnt work on notgrid while in combat. Out of combat it works fine but in combat i won't work.

used macros:

/run if nil then CastSpellByName("Heal")end
/cast [help @mouseover] Heal

/run if nil then CastSpellByName("Dispel Magic")end
/cast [@mouseover] Dispel Magic

**Comment by DennisWG** [comment]
Hey,

this is because NotGrid disables the mouseover functionality when you're in combat. I've created a pull request at the NotGrid repository (https://github.com/gnwl/NotGrid/pull/19) in order to give you the option to enable it again, so make sure to keep an eye out for when it gets merged (if it gets merged).

Also, make sure to write `mouseover` in all lower-case letters. The macro shouldn't work at all the way you've written it.

**Comment by mohcow** [comment]
Thank you very much!
