### ISSUE TITLE
Not realy an issue - request.

### ISSUE THREAD

**Issue by vasecha** [DennisWG/CastModifier#5]
Hi. Thanks for the gerat work!
Any chanse to add those conditions?
/cast [button:1] spell
/cast [button:2] spell

And add /use for macro like this:
/use [button:1] item
/use [button:2] item

Im NOT a clicker, But it would be nice to have those options.
TY.

**Comment by DennisWG** [comment]
I don't care whether or not you're a clicker. Live and let live!

Regarding your /use request:
I was just thinking about adding /use alongside with /equip the other day, but I wasn't sure about how useful these would be. But since at least one of these have been requested, I'll add them in the future! But before that, I have to complete one or two other things first, so don't expect them in the next few days or so. :)

Regarding the button Conditional:
I don't see a way of implementing this as of right now because the Addon is waiting for chat commands instead of action bar button presses. So I don't know if there is a way to do this without rewriting the entire thing. But I'll look into it once I find the time to.

**Comment by vasecha** [comment]
You are such a great man. TY in andavance. :)

**Comment by DennisWG** [comment]
Implemented!
