### ISSUE TITLE
Mouseover on nameplates?

### ISSUE THREAD

**Issue by Larzie** [DennisWG/CastModifier#7]
Hey man, I used to macro everything in TBC on mouseover specially for using it on nameplates. It seems when using Shaguplates or nothing as nameplates it doesn't work with @mouseover. Could you take a look at it? I can't figure it out on my own >_< haha

**Comment by Larzie** [comment]
With the release of Elysium PvP, this bug suddenly got fixed itself. I have no idea why.

**Comment by Larzie** [comment]
With the latest Shaguplates this issue is solved. However ''Auto Shot'' and Mouseover doesn't work together. (/cast [@mouseover] Auto Shot). Any idea to work-around this one?

**Comment by DennisWG** [comment]
I'm unable to test this on Nostlysium since I'm not willing to sit through a 5-hour queue, but at least on the server I play on it'll interrupt your Auto Shot when you deselect your current target. Therefore it will either just switch back to your current target or, if you don't have one, interrupt Auto Shot altogether. So this might be a server side limitation.
Could you check if this is the case? Just select a target, cast Auto Shot, and then deselect your target and see if your Auto Shot gets interrupted. If so, then there's nothing I can do about this.

**Comment by spasut** [comment]
[@mouseOver] on pfUI unitframes doesn't work either. Can you please check it on Kronos3, dennis?
